#!/usr/bin/env python

Import('env')

env.servers_sources = []
env.add_source_files(env.servers_sources, "*.cpp")

SConscript('arvr/SCsub')
SConscript('camera/SCsub')
SConscript('physics/SCsub')
SConscript('physics_2d/SCsub')
SConscript('visual/SCsub')
SConscript('audio/SCsub')

env.Append(sources=env.servers_sources)
