#!/usr/bin/env python

Import('env')

from platform_methods import run_in_subprocess
import platform_osx_builders

files = [
    'platform/osx/crash_handler_osx.mm',
    'platform/osx/os_osx.mm',
    'platform/osx/godot_main_osx.mm',
    'platform/osx/semaphore_osx.cpp',
    'platform/osx/dir_access_osx.mm',
    'platform/osx/joypad_osx.cpp',
    'platform/osx/power_osx.cpp',
]

env.Append(sources=files)

if (env["debug_symbols"] == "full" or env["debug_symbols"] == "yes") and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_osx_builders.make_debug_osx))

