#!/usr/bin/env python

Import('env')

from platform_methods import run_in_subprocess
import platform_x11_builders

common_x11 = [
    "platform/x11/context_gl_x11.cpp",
    "platform/x11/crash_handler_x11.cpp",
    "platform/x11/os_x11.cpp",
    "platform/x11/key_mapping_x11.cpp",
    "platform/x11/joypad_linux.cpp",
    "platform/x11/power_x11.cpp",
    "platform/x11/detect_prime.cpp"
]

env.Append(sources=common_x11)

if (env["debug_symbols"] == "full" or env["debug_symbols"] == "yes") and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_x11_builders.make_debug_x11))
